spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/midas
    username: midas
    password: midaspw
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: midas-core-group
      auto-offset-reset: earliest
      enable-auto-commit: false
    properties:
      spring.json.trusted.packages: "*"

  flyway:
    enabled: false

midas:
  topic:
    name: tx-topic

logging:
  level:
    root: INFO
